vocab_size: 5
max_seq_len: 60
sample_size: 4000
sample_size_test: 1000
num_epoch: 800
batch_size: 64
num_heads: 1
fancy_opt: False
use_wd: True
lr: 0.001
wd: 5e-4
wd_2: 0
num_layers: 3

add_embed: True
train_from_scratch: False
residual: True
dropout: 0.1
norm: True
outdim_truncate: False
trainable: [True, True]


# save_epoch: 50
ckpt_path: ./save/layer3/run1


